# Generated by Django 4.2.7 on 2023-11-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_remove_register_conpass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
