# Generated by Django 4.2.7 on 2023-11-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegeapp', '0007_remove_course_department_delete_regapply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('dob', models.SlugField(max_length=250, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250, unique=True)),
                ('phone', models.CharField(max_length=250, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('address', models.CharField(max_length=250, unique=True)),
                ('dept', models.CharField(max_length=250, unique=True)),
                ('course', models.CharField(max_length=250, unique=True)),
                ('purpose', models.CharField(max_length=250, unique=True)),
                ('materials', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.department')),
            ],
        ),
    ]
