# Generated by Django 4.2.7 on 2023-11-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.DeleteModel(
            name='Regapply',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
